### ISSUE TITLE
Ember 3.8 - replaceState on History error after deploying gh-pages

### ISSUE THREAD

**Issue by crhayes** [ember-learn/ember-cli-addon-docs#333]
Hello,

I recently ran through the Quickstart with a newly created addon (Ember 3.8) and received the following error:

![image](https://user-images.githubusercontent.com/727536/53775045-f5335080-3ebe-11e9-9a03-7bdd10a13575.png)

Any ideas as to what I need to fix?

Thanks!

**Comment by crhayes** [comment]
I've tried a number of combinations of dependencies and discovered that (using `ember-cli-addon-docs: 0.6.5`):

- `ember-source: 3.8.*` with `ember-cli: 3.7.*` works
- `ember-source: 3.8.*` with `ember-cli: 3.8.*` does not work

**Comment by miguelcobain** [comment]
I can confirm this. It has something to do with those double slashes on ember-cli 3.8.x.

**Comment by ming-codes** [comment]
Try master. I think is already fixed from one of my previous PR 😄

**Comment by samselikoff** [comment]
@crhayes @miguelcobain just released 0.6.6, want to give it a shot?

**Comment by miguelcobain** [comment]
It works for me!

**Comment by rwwagner90** [comment]
I think I am still seeing this in ember-cli 3.9 and latest addon docs. Is anyone else hitting this again?
